//collection of the all action types, used for better code consistency

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const TOKEN_CHECKED = 'TOKEN_CHECKED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';

export const SET_SIDEBAR = 'SET_SIDEBAR';
export const SET_SIDEBAR_LOADING = 'SET_SIDEBAR_LOADING';

export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const CHANGE_MATERIAL = 'CHANGE_MATERIAL';
export const CHANGE_PLATFORM = 'CHANGE_PLATFORM';

export const SET_USERS = 'SET_USERS';
export const SET_LOADING_USERS = 'SET_LOADING_USERS';
export const SET_LOADING_USER_ROLES = 'SET_LOADING_USER_ROLES';
export const SET_USER_ROLES = 'SET_USER_ROLES';
export const SET_USER_EMAIL_ERROR = 'SET_USER_EMAIL_ERROR';
export const SET_LOADING_USER = 'SET_LOADING_USER';
export const SET_USER = 'SET_USER';
export const EDIT_USER = 'EDIT_USER';

export const SET_COMPANIES = 'SET_COMPANIES';
export const SET_LOADING_COMPANIES = 'SET_LOADING_COMPANIES';
export const ADD_COMPANY = 'ADD_COMPANY';
export const SET_LOADING_COMPANY = 'SET_LOADING_COMPANY';
export const SET_COMPANY = 'SET_COMPANY';
export const EDIT_COMPANY = 'EDIT_COMPANY';

export const SET_TASKS = 'SET_TASKS';
export const SET_LOADING_TASKS = 'SET_LOADING_TASKS';
export const SET_OPENED_ID = 'SET_OPENED_ID';
export const ADD_TASKS = 'ADD_TASKS';
export const SET_TASK_STATUSES_LOADING = 'SET_TASK_STATUSES_LOADING';
export const SET_TASK_STATUSES = 'SET_TASK_STATUSES';
export const SET_TASK_PROJECTS_LOADING = 'SET_TASK_PROJECTS_LOADING';
export const SET_TASK_PROJECTS = 'SET_TASK_PROJECTS';
export const SET_TASK_COMPANIES_LOADING = 'SET_TASK_COMPANIES_LOADING';
export const SET_TASK_COMPANIES = 'SET_TASK_COMPANIES';
export const SET_TASK_UNITS_LOADING = 'SET_TASK_UNITS_LOADING';
export const SET_TASK_UNITS = 'SET_TASK_UNITS';
export const SET_TASK_TAGS_LOADING = 'SET_TASK_TAGS_LOADING';
export const SET_TASK_TAGS = 'SET_TASK_TAGS';
export const SET_TASK_SOLVERS = 'SET_TASK_SOLVERS';
export const SET_TASK_LOADING = 'SET_TASK_LOADING';
export const SET_TASK = 'SET_TASK';
export const EDIT_TASK = 'EDIT_TASK';

///
export const SET_PROJECTS = 'SET_PROJECTS';
export const START_LOADING_PROJECTS = 'START_LOADING_PROJECTS';
export const SET_UNITS = 'SET_UNITS';
export const START_LOADING = 'START_LOADING';
export const SET_TASK_ATTRIBUTES = 'SET_TASK_ATTRIBUTES';
export const EDIT_TASK_LIST = 'EDIT_TASK_LIST';
export const DELETE_TASK = 'DELETE_TASK';
export const SET_FILTERS = 'SET_FILTERS';
export const SET_LAST_TASK = 'SET_LAST_TASK';
export const ADD_NEW_TASK = 'ADD_NEW_TASK';


export const SET_COMMENTS = 'SET_COMMENTS';
export const START_LOADING_COMMENTS = 'START_LOADING_COMMENTS';
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';

export const SET_ITEMS = 'SET_ITEMS';
export const START_LOADING_ITEMS = 'START_LOADING_ITEMS';
export const ADD_NEW_ITEM = 'ADD_NEW_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const EDIT_ITEM_LIST = 'EDIT_ITEM_LIST';
export const SET_ITEM = 'SET_ITEM';

export const START_LOADING_USER = 'START_LOADING_USER';
export const SET_USER_ATTRIBUTES = 'SET_USER_ATTRIBUTES';
export const ADD_USER = 'ADD_USER';
export const EDIT_USER_LIST = 'EDIT_USER_LIST';
export const SET_ASSIGNERS = 'SET_ASSIGNERS';


export const START_LOADING_SEARCH = 'START_LOADING_SEARCH';
export const SET_SEARCH_ATTRIBUTES = 'SET_SEARCH_ATTRIBUTES';

export const SET_LABELS = 'SET_LABELS';
