export const LOGIN_START = 'AUTH_LOGIN_START';
export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const LOGIN_LOGOUT = 'AUTH_LOGOUT';

export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const CHANGE_MATERIAL = 'CHANGE_MATERIAL';
export const CHANGE_PLATFORM = 'CHANGE_PLATFORM';

export const SET_TASKS = 'SET_TASKS';
export const SET_PROJECTS = 'SET_PROJECTS';
export const SET_COMPANIES = 'SET_COMPANIES';
export const SET_STATUSES = 'SET_STATUSES';
export const SET_USERS = 'SET_USERS';
export const SET_CUSTOM_ATTRIBUTES = 'SET_CUSTOM_ATTRIBUTES';
