export const LOGIN_START = 'AUTH_LOGIN_START';
export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const LOGIN_LOGOUT = 'AUTH_LOGOUT';

export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const CHANGE_MATERIAL = 'CHANGE_MATERIAL';
export const CHANGE_PLATFORM = 'CHANGE_PLATFORM';

export const SET_TASKS_AND_PROJECTS = 'SET_TASKS_AND_PROJECTS';
export const SET_TASKS = 'SET_TASKS';
export const SET_PROJECTS = 'SET_PROJECTS';
export const SET_COMPANIES = 'SET_COMPANIES';
export const SET_STATUSES = 'SET_STATUSES';
export const SET_USERS = 'SET_USERS';
export const SET_CUSTOM_ATTRIBUTES = 'SET_CUSTOM_ATTRIBUTES';
export const SET_UNITS = 'SET_UNITS';
export const SET_TASK = 'SET_TASK';
export const START_LOADING = 'START_LOADING';
export const SET_TASK_ATTRIBUTES = 'SET_TASK_ATTRIBUTES';
export const EDIT_TASK_LIST = 'EDIT_TASK_LIST';
export const ADD_TO_TASK_LIST = 'ADD_TO_TASK_LIST';

export const SET_COMMENTS = 'SET_COMMENTS';
export const START_LOADING_COMMENTS = 'START_LOADING_COMMENTS';
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';
